spring:
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always
      data-locations: classpath:init-data.sql
  datasource:
    url: jdbc:mysql://dangch-mysql:53306/id_mysql_database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mysql_root_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    defer-datasource-initialization: true
  data:
    redis:
      host: dangch-redis
      port: 56379
      password: redis_password
  kafka:
    bootstrap-servers: dangch-kafka:59092

server:
  port: 58082

security:
  external-jwt:
    public-key-path: file:../secrets/jwt-public.pem
    private-key-path: file:../secrets/jwt-private.pem
    access-ttl: PT60M
    refresh-ttl: P7D
  internal-jwt:
    ttl: PT10M

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dangch-eureka:58761/eureka
  instance:
    prefer-ip-address: true
    hostname: dangch-auth
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.security: INFO

app:
  frontend:
    reset-password-url: http://localhost:5173/

# Required declarations (But it doesn't need to have value.)
internal:
  api:
    auth-service: repo-auth
    token-path: /oauth/token
    client-id:
    client-secret:

kafka:
  topics:
    notification: notification.in-app
    file: storage.file
    mail: notification.mail