spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  autoconfigure:
    exclude:
      # Database Off
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  kafka:
    bootstrap-servers: dangch-kafka:59092
    consumer:
      group-id: realtime-service
      auto-offset-reset: latest

server:
  port: 58084

security:
  external-jwt:
    public-key-path: file:../secrets/jwt-public.pem

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dangch-eureka:58761/eureka
  instance:
    prefer-ip-address: true
    hostname: dangch-realtime
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework:
      cloud.gateway: INFO
      web.reactive:
        socket:
          server: DEBUG
      messaging: DEBUG
    web.reactive.socket: DEBUG

# Required declarations (But it doesn't need to have value.)
internal:
  api:
    auth-service: repo-auth
    token-path: /oauth/token
    client-id: HgdLhl5jxabqSmvGmazt3tLX
    client-secret: DDm8amT7IAScZgnsx0bTeIjWm37NTep0

kafka:
  topics:
    notification: notification.in-app
    file: storage.file
    mail: notification.mail